
package com.lb.jwitter.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import com.lb.jwitter.service.CommonService;

/**
 * This class was generated by Apache CXF 2.0.9
 * Mon Sep 05 09:39:24 ICT 2016
 * Generated source version: 2.0.9
 * 
 */

@WebServiceClient(name = "CommonServiceService", 
                  wsdlLocation = "file:/C:/PROJECT/VIET%20SOLUTION/CODE%20MAU/WEB%20SERVICE/CORE-Client/src/main/resources/wsdl/core/CommonService.wsdl",
                  targetNamespace = "http://service.jwitter.lb.com/") 
public class CommonServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://service.jwitter.lb.com/", "CommonServiceService");
    public final static QName CommonServicePort = new QName("http://service.jwitter.lb.com/", "CommonServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/PROJECT/VIET%20SOLUTION/CODE%20MAU/WEB%20SERVICE/CORE-Client/src/main/resources/wsdl/core/CommonService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/C:/PROJECT/VIET%20SOLUTION/CODE%20MAU/WEB%20SERVICE/CORE-Client/src/main/resources/wsdl/core/CommonService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public CommonServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CommonServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CommonServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns CommonServicePort
     */
    @WebEndpoint(name = "CommonServicePort")
    public CommonService getCommonServicePort() {
        return super.getPort(CommonServicePort, CommonService.class);
    }

}
