
package com.lb.jwitter.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.0.9
 * Mon Sep 05 09:39:22 ICT 2016
 * Generated source version: 2.0.9
 * 
 */

@WebService(targetNamespace = "http://service.jwitter.lb.com/", name = "Tbl_CanBoService")

public interface TblCanBoService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findtbl_CanBoByHQL", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindtblCanBoByHQL")
    @ResponseWrapper(localName = "findtbl_CanBoByHQLResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindtblCanBoByHQLResponse")
    @WebMethod(operationName = "findtbl_CanBoByHQL")
    public java.util.List<com.lb.jwitter.service.TblCanBo> findtblCanBoByHQL(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAlltbl_CanBo", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindAlltblCanBo")
    @ResponseWrapper(localName = "findAlltbl_CanBoResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindAlltblCanBoResponse")
    @WebMethod(operationName = "findAlltbl_CanBo")
    public java.util.List<com.lb.jwitter.service.TblCanBo> findAlltblCanBo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @RequestWrapper(localName = "deleteListtbl_CanBo", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeleteListtblCanBo")
    @ResponseWrapper(localName = "deleteListtbl_CanBoResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeleteListtblCanBoResponse")
    @WebMethod(operationName = "deleteListtbl_CanBo")
    public void deleteListtblCanBo(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.String> arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findtbl_CanBoByCondition", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindtblCanBoByCondition")
    @ResponseWrapper(localName = "findtbl_CanBoByConditionResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindtblCanBoByConditionResponse")
    @WebMethod(operationName = "findtbl_CanBoByCondition")
    public java.util.List<com.lb.jwitter.service.TblCanBo> findtblCanBoByCondition(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.lb.jwitter.service.ConditionReport> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    );

    @RequestWrapper(localName = "updatetbl_CanBo", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.UpdatetblCanBo")
    @ResponseWrapper(localName = "updatetbl_CanBoResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.UpdatetblCanBoResponse")
    @WebMethod(operationName = "updatetbl_CanBo")
    public void updatetblCanBo(
        @WebParam(name = "arg0", targetNamespace = "")
        com.lb.jwitter.service.TblCanBo arg0
    );

    @RequestWrapper(localName = "deletetbl_CanBo", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeletetblCanBo")
    @ResponseWrapper(localName = "deletetbl_CanBoResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeletetblCanBoResponse")
    @WebMethod(operationName = "deletetbl_CanBo")
    public void deletetblCanBo(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createtbl_CanBo", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CreatetblCanBo")
    @ResponseWrapper(localName = "createtbl_CanBoResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CreatetblCanBoResponse")
    @WebMethod(operationName = "createtbl_CanBo")
    public java.lang.Long createtblCanBo(
        @WebParam(name = "arg0", targetNamespace = "")
        com.lb.jwitter.service.TblCanBo arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "counttbl_CanBoByCondition", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CounttblCanBoByCondition")
    @ResponseWrapper(localName = "counttbl_CanBoByConditionResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CounttblCanBoByConditionResponse")
    @WebMethod(operationName = "counttbl_CanBoByCondition")
    public int counttblCanBoByCondition(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.lb.jwitter.service.ConditionReport> arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "gettbl_CanBo", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.GettblCanBo")
    @ResponseWrapper(localName = "gettbl_CanBoResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.GettblCanBoResponse")
    @WebMethod(operationName = "gettbl_CanBo")
    public com.lb.jwitter.service.TblCanBo gettblCanBo(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );
}
