
package com.lb.jwitter.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import com.lb.jwitter.service.TblDBTableService;

/**
 * This class was generated by Apache CXF 2.0.9
 * Mon Sep 05 09:39:24 ICT 2016
 * Generated source version: 2.0.9
 * 
 */

@WebServiceClient(name = "Tbl_DBTableServiceService", 
                  wsdlLocation = "file:/C:/PROJECT/VIET%20SOLUTION/CODE%20MAU/WEB%20SERVICE/CORE-Client/src/main/resources/wsdl/core/Tbl_DBTableService.wsdl",
                  targetNamespace = "http://service.jwitter.lb.com/") 
public class TblDBTableServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://service.jwitter.lb.com/", "Tbl_DBTableServiceService");
    public final static QName TblDBTableServicePort = new QName("http://service.jwitter.lb.com/", "Tbl_DBTableServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/PROJECT/VIET%20SOLUTION/CODE%20MAU/WEB%20SERVICE/CORE-Client/src/main/resources/wsdl/core/Tbl_DBTableService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/C:/PROJECT/VIET%20SOLUTION/CODE%20MAU/WEB%20SERVICE/CORE-Client/src/main/resources/wsdl/core/Tbl_DBTableService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public TblDBTableServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TblDBTableServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TblDBTableServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns TblDBTableServicePort
     */
    @WebEndpoint(name = "Tbl_DBTableServicePort")
    public TblDBTableService getTblDBTableServicePort() {
        return super.getPort(TblDBTableServicePort, TblDBTableService.class);
    }

}
