
package com.lb.jwitter.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import com.lb.jwitter.service.TblDonViService;

/**
 * This class was generated by Apache CXF 2.0.9
 * Wed Feb 08 16:23:07 ICT 2017
 * Generated source version: 2.0.9
 * 
 */

@WebServiceClient(name = "Tbl_DonViServiceService", 
                  wsdlLocation = "file:/C:/PROJECT/VIET%20SOLUTION/CODE%20MAU/WEB%20SERVICE%20V2/CORE-Client/src/main/resources/wsdl/core/Tbl_DonViService.wsdl",
                  targetNamespace = "http://service.jwitter.lb.com/") 
public class TblDonViServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://service.jwitter.lb.com/", "Tbl_DonViServiceService");
    public final static QName TblDonViServicePort = new QName("http://service.jwitter.lb.com/", "Tbl_DonViServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/PROJECT/VIET%20SOLUTION/CODE%20MAU/WEB%20SERVICE%20V2/CORE-Client/src/main/resources/wsdl/core/Tbl_DonViService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/C:/PROJECT/VIET%20SOLUTION/CODE%20MAU/WEB%20SERVICE%20V2/CORE-Client/src/main/resources/wsdl/core/Tbl_DonViService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public TblDonViServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TblDonViServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TblDonViServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns TblDonViServicePort
     */
    @WebEndpoint(name = "Tbl_DonViServicePort")
    public TblDonViService getTblDonViServicePort() {
        return super.getPort(TblDonViServicePort, TblDonViService.class);
    }

}
