
package com.lb.jwitter.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import com.lb.jwitter.service.TblMenuService;

/**
 * This class was generated by Apache CXF 2.0.9
 * Mon Sep 05 09:39:23 ICT 2016
 * Generated source version: 2.0.9
 * 
 */

@WebServiceClient(name = "Tbl_MenuServiceService", 
                  wsdlLocation = "file:/C:/PROJECT/VIET%20SOLUTION/CODE%20MAU/WEB%20SERVICE/CORE-Client/src/main/resources/wsdl/core/Tbl_MenuService.wsdl",
                  targetNamespace = "http://service.jwitter.lb.com/") 
public class TblMenuServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://service.jwitter.lb.com/", "Tbl_MenuServiceService");
    public final static QName TblMenuServicePort = new QName("http://service.jwitter.lb.com/", "Tbl_MenuServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/PROJECT/VIET%20SOLUTION/CODE%20MAU/WEB%20SERVICE/CORE-Client/src/main/resources/wsdl/core/Tbl_MenuService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/C:/PROJECT/VIET%20SOLUTION/CODE%20MAU/WEB%20SERVICE/CORE-Client/src/main/resources/wsdl/core/Tbl_MenuService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public TblMenuServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TblMenuServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TblMenuServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns TblMenuServicePort
     */
    @WebEndpoint(name = "Tbl_MenuServicePort")
    public TblMenuService getTblMenuServicePort() {
        return super.getPort(TblMenuServicePort, TblMenuService.class);
    }

}
