
package com.lb.jwitter.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import com.lb.jwitter.service.TblNhomQuyenService;

/**
 * This class was generated by Apache CXF 2.0.9
 * Mon Sep 05 09:39:23 ICT 2016
 * Generated source version: 2.0.9
 * 
 */

@WebServiceClient(name = "Tbl_NhomQuyenServiceService", 
                  wsdlLocation = "file:/C:/PROJECT/VIET%20SOLUTION/CODE%20MAU/WEB%20SERVICE/CORE-Client/src/main/resources/wsdl/core/Tbl_NhomQuyenService.wsdl",
                  targetNamespace = "http://service.jwitter.lb.com/") 
public class TblNhomQuyenServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://service.jwitter.lb.com/", "Tbl_NhomQuyenServiceService");
    public final static QName TblNhomQuyenServicePort = new QName("http://service.jwitter.lb.com/", "Tbl_NhomQuyenServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/PROJECT/VIET%20SOLUTION/CODE%20MAU/WEB%20SERVICE/CORE-Client/src/main/resources/wsdl/core/Tbl_NhomQuyenService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/C:/PROJECT/VIET%20SOLUTION/CODE%20MAU/WEB%20SERVICE/CORE-Client/src/main/resources/wsdl/core/Tbl_NhomQuyenService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public TblNhomQuyenServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TblNhomQuyenServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TblNhomQuyenServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns TblNhomQuyenServicePort
     */
    @WebEndpoint(name = "Tbl_NhomQuyenServicePort")
    public TblNhomQuyenService getTblNhomQuyenServicePort() {
        return super.getPort(TblNhomQuyenServicePort, TblNhomQuyenService.class);
    }

}
