
package com.lb.jwitter.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.0.9
 * Mon Sep 05 09:39:25 ICT 2016
 * Generated source version: 2.0.9
 * 
 */

@WebService(targetNamespace = "http://service.jwitter.lb.com/", name = "Tbl_QLDTLT_OptionGroupService")

public interface TblQLDTLTOptionGroupService {

    @RequestWrapper(localName = "deleteListTbl_QLDTLT_OptionGroup", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeleteListTblQLDTLTOptionGroup")
    @ResponseWrapper(localName = "deleteListTbl_QLDTLT_OptionGroupResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeleteListTblQLDTLTOptionGroupResponse")
    @WebMethod(operationName = "deleteListTbl_QLDTLT_OptionGroup")
    public void deleteListTblQLDTLTOptionGroup(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.String> arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createTbl_QLDTLT_OptionGroup", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CreateTblQLDTLTOptionGroup")
    @ResponseWrapper(localName = "createTbl_QLDTLT_OptionGroupResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CreateTblQLDTLTOptionGroupResponse")
    @WebMethod(operationName = "createTbl_QLDTLT_OptionGroup")
    public java.lang.Long createTblQLDTLTOptionGroup(
        @WebParam(name = "arg0", targetNamespace = "")
        com.lb.jwitter.service.TblQLDTLTOptionGroup arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "countTbl_QLDTLT_OptionGroupByCondition", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CountTblQLDTLTOptionGroupByCondition")
    @ResponseWrapper(localName = "countTbl_QLDTLT_OptionGroupByConditionResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CountTblQLDTLTOptionGroupByConditionResponse")
    @WebMethod(operationName = "countTbl_QLDTLT_OptionGroupByCondition")
    public int countTblQLDTLTOptionGroupByCondition(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.lb.jwitter.service.ConditionReport> arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findTbl_QLDTLT_OptionGroupByCondition", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindTblQLDTLTOptionGroupByCondition")
    @ResponseWrapper(localName = "findTbl_QLDTLT_OptionGroupByConditionResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindTblQLDTLTOptionGroupByConditionResponse")
    @WebMethod(operationName = "findTbl_QLDTLT_OptionGroupByCondition")
    public java.util.List<com.lb.jwitter.service.TblQLDTLTOptionGroup> findTblQLDTLTOptionGroupByCondition(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.lb.jwitter.service.ConditionReport> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTbl_QLDTLT_OptionGroup", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.GetTblQLDTLTOptionGroup")
    @ResponseWrapper(localName = "getTbl_QLDTLT_OptionGroupResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.GetTblQLDTLTOptionGroupResponse")
    @WebMethod(operationName = "getTbl_QLDTLT_OptionGroup")
    public com.lb.jwitter.service.TblQLDTLTOptionGroup getTblQLDTLTOptionGroup(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @RequestWrapper(localName = "deleteTbl_QLDTLT_OptionGroup", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeleteTblQLDTLTOptionGroup")
    @ResponseWrapper(localName = "deleteTbl_QLDTLT_OptionGroupResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeleteTblQLDTLTOptionGroupResponse")
    @WebMethod(operationName = "deleteTbl_QLDTLT_OptionGroup")
    public void deleteTblQLDTLTOptionGroup(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @RequestWrapper(localName = "updateTbl_QLDTLT_OptionGroup", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.UpdateTblQLDTLTOptionGroup")
    @ResponseWrapper(localName = "updateTbl_QLDTLT_OptionGroupResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.UpdateTblQLDTLTOptionGroupResponse")
    @WebMethod(operationName = "updateTbl_QLDTLT_OptionGroup")
    public void updateTblQLDTLTOptionGroup(
        @WebParam(name = "arg0", targetNamespace = "")
        com.lb.jwitter.service.TblQLDTLTOptionGroup arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllTbl_QLDTLT_OptionGroup", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindAllTblQLDTLTOptionGroup")
    @ResponseWrapper(localName = "findAllTbl_QLDTLT_OptionGroupResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindAllTblQLDTLTOptionGroupResponse")
    @WebMethod(operationName = "findAllTbl_QLDTLT_OptionGroup")
    public java.util.List<com.lb.jwitter.service.TblQLDTLTOptionGroup> findAllTblQLDTLTOptionGroup(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findColumnTbl_QLDTLT_OptionGroupByCondition", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindColumnTblQLDTLTOptionGroupByCondition")
    @ResponseWrapper(localName = "findColumnTbl_QLDTLT_OptionGroupByConditionResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindColumnTblQLDTLTOptionGroupByConditionResponse")
    @WebMethod(operationName = "findColumnTbl_QLDTLT_OptionGroupByCondition")
    public java.util.List<java.lang.Object> findColumnTblQLDTLTOptionGroupByCondition(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.lb.jwitter.service.ConditionReport> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<java.lang.String> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryHQLTbl_QLDTLT_OptionGroup", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.QueryHQLTblQLDTLTOptionGroup")
    @ResponseWrapper(localName = "queryHQLTbl_QLDTLT_OptionGroupResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.QueryHQLTblQLDTLTOptionGroupResponse")
    @WebMethod(operationName = "queryHQLTbl_QLDTLT_OptionGroup")
    public java.util.List<com.lb.jwitter.service.TblQLDTLTOptionGroup> queryHQLTblQLDTLTOptionGroup(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    );
}
