
package com.lb.jwitter.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.0.9
 * Mon Sep 05 09:39:21 ICT 2016
 * Generated source version: 2.0.9
 * 
 */

@WebService(targetNamespace = "http://service.jwitter.lb.com/", name = "Tbl_Quyen_NhomQuyenService")

public interface TblQuyenNhomQuyenService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createtbl_Quyen_NhomQuyen", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CreatetblQuyenNhomQuyen")
    @ResponseWrapper(localName = "createtbl_Quyen_NhomQuyenResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CreatetblQuyenNhomQuyenResponse")
    @WebMethod(operationName = "createtbl_Quyen_NhomQuyen")
    public java.lang.Long createtblQuyenNhomQuyen(
        @WebParam(name = "arg0", targetNamespace = "")
        com.lb.jwitter.service.TblQuyenNhomQuyen arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAlltbl_Quyen_NhomQuyen", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindAlltblQuyenNhomQuyen")
    @ResponseWrapper(localName = "findAlltbl_Quyen_NhomQuyenResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindAlltblQuyenNhomQuyenResponse")
    @WebMethod(operationName = "findAlltbl_Quyen_NhomQuyen")
    public java.util.List<com.lb.jwitter.service.TblQuyenNhomQuyen> findAlltblQuyenNhomQuyen(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @RequestWrapper(localName = "updatetbl_Quyen_NhomQuyen", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.UpdatetblQuyenNhomQuyen")
    @ResponseWrapper(localName = "updatetbl_Quyen_NhomQuyenResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.UpdatetblQuyenNhomQuyenResponse")
    @WebMethod(operationName = "updatetbl_Quyen_NhomQuyen")
    public void updatetblQuyenNhomQuyen(
        @WebParam(name = "arg0", targetNamespace = "")
        com.lb.jwitter.service.TblQuyenNhomQuyen arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "gettbl_Quyen_NhomQuyen", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.GettblQuyenNhomQuyen")
    @ResponseWrapper(localName = "gettbl_Quyen_NhomQuyenResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.GettblQuyenNhomQuyenResponse")
    @WebMethod(operationName = "gettbl_Quyen_NhomQuyen")
    public com.lb.jwitter.service.TblQuyenNhomQuyen gettblQuyenNhomQuyen(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @RequestWrapper(localName = "deleteListtbl_Quyen_NhomQuyen", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeleteListtblQuyenNhomQuyen")
    @ResponseWrapper(localName = "deleteListtbl_Quyen_NhomQuyenResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeleteListtblQuyenNhomQuyenResponse")
    @WebMethod(operationName = "deleteListtbl_Quyen_NhomQuyen")
    public void deleteListtblQuyenNhomQuyen(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.String> arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findtbl_Quyen_NhomQuyenByCondition", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindtblQuyenNhomQuyenByCondition")
    @ResponseWrapper(localName = "findtbl_Quyen_NhomQuyenByConditionResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindtblQuyenNhomQuyenByConditionResponse")
    @WebMethod(operationName = "findtbl_Quyen_NhomQuyenByCondition")
    public java.util.List<com.lb.jwitter.service.TblQuyenNhomQuyen> findtblQuyenNhomQuyenByCondition(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.lb.jwitter.service.ConditionReport> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    );

    @RequestWrapper(localName = "deletetbl_Quyen_NhomQuyen", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeletetblQuyenNhomQuyen")
    @ResponseWrapper(localName = "deletetbl_Quyen_NhomQuyenResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeletetblQuyenNhomQuyenResponse")
    @WebMethod(operationName = "deletetbl_Quyen_NhomQuyen")
    public void deletetblQuyenNhomQuyen(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "counttbl_Quyen_NhomQuyenByCondition", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CounttblQuyenNhomQuyenByCondition")
    @ResponseWrapper(localName = "counttbl_Quyen_NhomQuyenByConditionResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CounttblQuyenNhomQuyenByConditionResponse")
    @WebMethod(operationName = "counttbl_Quyen_NhomQuyenByCondition")
    public int counttblQuyenNhomQuyenByCondition(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.lb.jwitter.service.ConditionReport> arg0
    );
}
