
package com.lb.jwitter.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import com.lb.jwitter.service.TblQLDTLogService;

/**
 * This class was generated by Apache CXF 2.0.9
 * Mon Sep 05 09:39:19 ICT 2016
 * Generated source version: 2.0.9
 * 
 */

@WebServiceClient(name = "Tbl_QLDT_LogServiceService", 
                  wsdlLocation = "file:/C:/PROJECT/VIET%20SOLUTION/CODE%20MAU/WEB%20SERVICE/CORE-Client/src/main/resources/wsdl/core/Tbl_QLDT_LogService.wsdl",
                  targetNamespace = "http://service.jwitter.lb.com/") 
public class TblQLDTLogServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://service.jwitter.lb.com/", "Tbl_QLDT_LogServiceService");
    public final static QName TblQLDTLogServicePort = new QName("http://service.jwitter.lb.com/", "Tbl_QLDT_LogServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/PROJECT/VIET%20SOLUTION/CODE%20MAU/WEB%20SERVICE/CORE-Client/src/main/resources/wsdl/core/Tbl_QLDT_LogService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/C:/PROJECT/VIET%20SOLUTION/CODE%20MAU/WEB%20SERVICE/CORE-Client/src/main/resources/wsdl/core/Tbl_QLDT_LogService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public TblQLDTLogServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TblQLDTLogServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TblQLDTLogServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns TblQLDTLogServicePort
     */
    @WebEndpoint(name = "Tbl_QLDT_LogServicePort")
    public TblQLDTLogService getTblQLDTLogServicePort() {
        return super.getPort(TblQLDTLogServicePort, TblQLDTLogService.class);
    }

}
