
package com.lb.jwitter.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.0.9
 * Mon Sep 05 09:39:23 ICT 2016
 * Generated source version: 2.0.9
 * 
 */

@WebService(targetNamespace = "http://service.jwitter.lb.com/", name = "Tbl_QuyenService")

public interface TblQuyenService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findtbl_QuyenByCondition", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindtblQuyenByCondition")
    @ResponseWrapper(localName = "findtbl_QuyenByConditionResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindtblQuyenByConditionResponse")
    @WebMethod(operationName = "findtbl_QuyenByCondition")
    public java.util.List<com.lb.jwitter.service.TblQuyen> findtblQuyenByCondition(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.lb.jwitter.service.ConditionReport> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    );

    @RequestWrapper(localName = "deletetbl_Quyen", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeletetblQuyen")
    @ResponseWrapper(localName = "deletetbl_QuyenResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeletetblQuyenResponse")
    @WebMethod(operationName = "deletetbl_Quyen")
    public void deletetblQuyen(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "counttbl_QuyenByCondition", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CounttblQuyenByCondition")
    @ResponseWrapper(localName = "counttbl_QuyenByConditionResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CounttblQuyenByConditionResponse")
    @WebMethod(operationName = "counttbl_QuyenByCondition")
    public int counttblQuyenByCondition(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.lb.jwitter.service.ConditionReport> arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createtbl_Quyen", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CreatetblQuyen")
    @ResponseWrapper(localName = "createtbl_QuyenResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CreatetblQuyenResponse")
    @WebMethod(operationName = "createtbl_Quyen")
    public java.lang.Long createtblQuyen(
        @WebParam(name = "arg0", targetNamespace = "")
        com.lb.jwitter.service.TblQuyen arg0
    );

    @RequestWrapper(localName = "deleteListtbl_Quyen", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeleteListtblQuyen")
    @ResponseWrapper(localName = "deleteListtbl_QuyenResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeleteListtblQuyenResponse")
    @WebMethod(operationName = "deleteListtbl_Quyen")
    public void deleteListtblQuyen(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.String> arg0
    );

    @RequestWrapper(localName = "updatetbl_Quyen", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.UpdatetblQuyen")
    @ResponseWrapper(localName = "updatetbl_QuyenResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.UpdatetblQuyenResponse")
    @WebMethod(operationName = "updatetbl_Quyen")
    public void updatetblQuyen(
        @WebParam(name = "arg0", targetNamespace = "")
        com.lb.jwitter.service.TblQuyen arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "gettbl_Quyen", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.GettblQuyen")
    @ResponseWrapper(localName = "gettbl_QuyenResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.GettblQuyenResponse")
    @WebMethod(operationName = "gettbl_Quyen")
    public com.lb.jwitter.service.TblQuyen gettblQuyen(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAlltbl_Quyen", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindAlltblQuyen")
    @ResponseWrapper(localName = "findAlltbl_QuyenResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindAlltblQuyenResponse")
    @WebMethod(operationName = "findAlltbl_Quyen")
    public java.util.List<com.lb.jwitter.service.TblQuyen> findAlltblQuyen(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
