
package com.lb.jwitter.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.0.9
 * Mon Sep 05 09:39:19 ICT 2016
 * Generated source version: 2.0.9
 * 
 */

@WebService(targetNamespace = "http://service.jwitter.lb.com/", name = "Tbl_QLDT_LogService")

public interface TblQLDTLogService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAlltbl_QLDT_Log", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindAlltblQLDTLog")
    @ResponseWrapper(localName = "findAlltbl_QLDT_LogResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindAlltblQLDTLogResponse")
    @WebMethod(operationName = "findAlltbl_QLDT_Log")
    public java.util.List<com.lb.jwitter.service.TblQLDTLog> findAlltblQLDTLog(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createtbl_QLDT_Log", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CreatetblQLDTLog")
    @ResponseWrapper(localName = "createtbl_QLDT_LogResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CreatetblQLDTLogResponse")
    @WebMethod(operationName = "createtbl_QLDT_Log")
    public java.lang.Long createtblQLDTLog(
        @WebParam(name = "arg0", targetNamespace = "")
        com.lb.jwitter.service.TblQLDTLog arg0
    );

    @RequestWrapper(localName = "deletetbl_QLDT_Log", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeletetblQLDTLog")
    @ResponseWrapper(localName = "deletetbl_QLDT_LogResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeletetblQLDTLogResponse")
    @WebMethod(operationName = "deletetbl_QLDT_Log")
    public void deletetblQLDTLog(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "gettbl_QLDT_Log", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.GettblQLDTLog")
    @ResponseWrapper(localName = "gettbl_QLDT_LogResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.GettblQLDTLogResponse")
    @WebMethod(operationName = "gettbl_QLDT_Log")
    public com.lb.jwitter.service.TblQLDTLog gettblQLDTLog(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findtbl_QLDT_LogByCondition", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindtblQLDTLogByCondition")
    @ResponseWrapper(localName = "findtbl_QLDT_LogByConditionResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindtblQLDTLogByConditionResponse")
    @WebMethod(operationName = "findtbl_QLDT_LogByCondition")
    public java.util.List<com.lb.jwitter.service.TblQLDTLog> findtblQLDTLogByCondition(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.lb.jwitter.service.ConditionReport> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findColumntbl_QLDT_LogByCondition", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindColumntblQLDTLogByCondition")
    @ResponseWrapper(localName = "findColumntbl_QLDT_LogByConditionResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindColumntblQLDTLogByConditionResponse")
    @WebMethod(operationName = "findColumntbl_QLDT_LogByCondition")
    public java.util.List<java.lang.Object> findColumntblQLDTLogByCondition(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.lb.jwitter.service.ConditionReport> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<java.lang.String> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3
    );

    @RequestWrapper(localName = "deleteListtbl_QLDT_Log", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeleteListtblQLDTLog")
    @ResponseWrapper(localName = "deleteListtbl_QLDT_LogResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeleteListtblQLDTLogResponse")
    @WebMethod(operationName = "deleteListtbl_QLDT_Log")
    public void deleteListtblQLDTLog(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.String> arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "counttbl_QLDT_LogByCondition", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CounttblQLDTLogByCondition")
    @ResponseWrapper(localName = "counttbl_QLDT_LogByConditionResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CounttblQLDTLogByConditionResponse")
    @WebMethod(operationName = "counttbl_QLDT_LogByCondition")
    public int counttblQLDTLogByCondition(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.lb.jwitter.service.ConditionReport> arg0
    );

    @RequestWrapper(localName = "updatetbl_QLDT_Log", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.UpdatetblQLDTLog")
    @ResponseWrapper(localName = "updatetbl_QLDT_LogResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.UpdatetblQLDTLogResponse")
    @WebMethod(operationName = "updatetbl_QLDT_Log")
    public void updatetblQLDTLog(
        @WebParam(name = "arg0", targetNamespace = "")
        com.lb.jwitter.service.TblQLDTLog arg0
    );
}
