
package com.lb.jwitter.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import com.lb.jwitter.service.TblQuyenChiTietService;

/**
 * This class was generated by Apache CXF 2.0.9
 * Mon Sep 05 09:39:22 ICT 2016
 * Generated source version: 2.0.9
 * 
 */

@WebServiceClient(name = "Tbl_Quyen_ChiTietServiceService", 
                  wsdlLocation = "file:/C:/PROJECT/VIET%20SOLUTION/CODE%20MAU/WEB%20SERVICE/CORE-Client/src/main/resources/wsdl/core/Tbl_Quyen_ChiTietService.wsdl",
                  targetNamespace = "http://service.jwitter.lb.com/") 
public class TblQuyenChiTietServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://service.jwitter.lb.com/", "Tbl_Quyen_ChiTietServiceService");
    public final static QName TblQuyenChiTietServicePort = new QName("http://service.jwitter.lb.com/", "Tbl_Quyen_ChiTietServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/PROJECT/VIET%20SOLUTION/CODE%20MAU/WEB%20SERVICE/CORE-Client/src/main/resources/wsdl/core/Tbl_Quyen_ChiTietService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/C:/PROJECT/VIET%20SOLUTION/CODE%20MAU/WEB%20SERVICE/CORE-Client/src/main/resources/wsdl/core/Tbl_Quyen_ChiTietService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public TblQuyenChiTietServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TblQuyenChiTietServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TblQuyenChiTietServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns TblQuyenChiTietServicePort
     */
    @WebEndpoint(name = "Tbl_Quyen_ChiTietServicePort")
    public TblQuyenChiTietService getTblQuyenChiTietServicePort() {
        return super.getPort(TblQuyenChiTietServicePort, TblQuyenChiTietService.class);
    }

}
