
package com.lb.jwitter.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import com.lb.jwitter.service.TblQLDTLTOptionService;

/**
 * This class was generated by Apache CXF 2.0.9
 * Mon Sep 05 09:39:26 ICT 2016
 * Generated source version: 2.0.9
 * 
 */

@WebServiceClient(name = "Tbl_QLDTLT_OptionServiceService", 
                  wsdlLocation = "file:/C:/PROJECT/VIET%20SOLUTION/CODE%20MAU/WEB%20SERVICE/CORE-Client/src/main/resources/wsdl/core/Tbl_QLDTLT_OptionService.wsdl",
                  targetNamespace = "http://service.jwitter.lb.com/") 
public class TblQLDTLTOptionServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://service.jwitter.lb.com/", "Tbl_QLDTLT_OptionServiceService");
    public final static QName TblQLDTLTOptionServicePort = new QName("http://service.jwitter.lb.com/", "Tbl_QLDTLT_OptionServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/PROJECT/VIET%20SOLUTION/CODE%20MAU/WEB%20SERVICE/CORE-Client/src/main/resources/wsdl/core/Tbl_QLDTLT_OptionService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/C:/PROJECT/VIET%20SOLUTION/CODE%20MAU/WEB%20SERVICE/CORE-Client/src/main/resources/wsdl/core/Tbl_QLDTLT_OptionService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public TblQLDTLTOptionServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TblQLDTLTOptionServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TblQLDTLTOptionServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns TblQLDTLTOptionServicePort
     */
    @WebEndpoint(name = "Tbl_QLDTLT_OptionServicePort")
    public TblQLDTLTOptionService getTblQLDTLTOptionServicePort() {
        return super.getPort(TblQLDTLTOptionServicePort, TblQLDTLTOptionService.class);
    }

}
