
package com.lb.jwitter.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.0.9
 * Mon Sep 05 09:39:22 ICT 2016
 * Generated source version: 2.0.9
 * 
 */

@WebService(targetNamespace = "http://service.jwitter.lb.com/", name = "Tbl_Quyen_ChiTietService")

public interface TblQuyenChiTietService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "gettbl_Quyen_ChiTiet", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.GettblQuyenChiTiet")
    @ResponseWrapper(localName = "gettbl_Quyen_ChiTietResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.GettblQuyenChiTietResponse")
    @WebMethod(operationName = "gettbl_Quyen_ChiTiet")
    public com.lb.jwitter.service.TblQuyenChiTiet gettblQuyenChiTiet(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @RequestWrapper(localName = "updatetbl_Quyen_ChiTiet", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.UpdatetblQuyenChiTiet")
    @ResponseWrapper(localName = "updatetbl_Quyen_ChiTietResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.UpdatetblQuyenChiTietResponse")
    @WebMethod(operationName = "updatetbl_Quyen_ChiTiet")
    public void updatetblQuyenChiTiet(
        @WebParam(name = "arg0", targetNamespace = "")
        com.lb.jwitter.service.TblQuyenChiTiet arg0
    );

    @RequestWrapper(localName = "deleteListtbl_Quyen_ChiTiet", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeleteListtblQuyenChiTiet")
    @ResponseWrapper(localName = "deleteListtbl_Quyen_ChiTietResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeleteListtblQuyenChiTietResponse")
    @WebMethod(operationName = "deleteListtbl_Quyen_ChiTiet")
    public void deleteListtblQuyenChiTiet(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.String> arg0
    );

    @RequestWrapper(localName = "deletetbl_Quyen_ChiTiet", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeletetblQuyenChiTiet")
    @ResponseWrapper(localName = "deletetbl_Quyen_ChiTietResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeletetblQuyenChiTietResponse")
    @WebMethod(operationName = "deletetbl_Quyen_ChiTiet")
    public void deletetblQuyenChiTiet(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "counttbl_Quyen_ChiTietByCondition", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CounttblQuyenChiTietByCondition")
    @ResponseWrapper(localName = "counttbl_Quyen_ChiTietByConditionResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CounttblQuyenChiTietByConditionResponse")
    @WebMethod(operationName = "counttbl_Quyen_ChiTietByCondition")
    public int counttblQuyenChiTietByCondition(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.lb.jwitter.service.ConditionReport> arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createtbl_Quyen_ChiTiet", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CreatetblQuyenChiTiet")
    @ResponseWrapper(localName = "createtbl_Quyen_ChiTietResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CreatetblQuyenChiTietResponse")
    @WebMethod(operationName = "createtbl_Quyen_ChiTiet")
    public java.lang.Long createtblQuyenChiTiet(
        @WebParam(name = "arg0", targetNamespace = "")
        com.lb.jwitter.service.TblQuyenChiTiet arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findtbl_Quyen_ChiTietByCondition", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindtblQuyenChiTietByCondition")
    @ResponseWrapper(localName = "findtbl_Quyen_ChiTietByConditionResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindtblQuyenChiTietByConditionResponse")
    @WebMethod(operationName = "findtbl_Quyen_ChiTietByCondition")
    public java.util.List<com.lb.jwitter.service.TblQuyenChiTiet> findtblQuyenChiTietByCondition(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.lb.jwitter.service.ConditionReport> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAlltbl_Quyen_ChiTiet", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindAlltblQuyenChiTiet")
    @ResponseWrapper(localName = "findAlltbl_Quyen_ChiTietResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindAlltblQuyenChiTietResponse")
    @WebMethod(operationName = "findAlltbl_Quyen_ChiTiet")
    public java.util.List<com.lb.jwitter.service.TblQuyenChiTiet> findAlltblQuyenChiTiet(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkRight", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CheckRight")
    @ResponseWrapper(localName = "checkRightResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CheckRightResponse")
    @WebMethod
    public boolean checkRight(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );
}
