
package com.lb.jwitter.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.0.9
 * Mon Sep 05 09:39:19 ICT 2016
 * Generated source version: 2.0.9
 * 
 */

@WebService(targetNamespace = "http://service.jwitter.lb.com/", name = "Tbl_QLDT_HTMLReportService")

public interface TblQLDTHTMLReportService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryHQLTbl_QLDT_HTMLReport", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.QueryHQLTblQLDTHTMLReport")
    @ResponseWrapper(localName = "queryHQLTbl_QLDT_HTMLReportResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.QueryHQLTblQLDTHTMLReportResponse")
    @WebMethod(operationName = "queryHQLTbl_QLDT_HTMLReport")
    public java.util.List<com.lb.jwitter.service.TblQLDTHTMLReport> queryHQLTblQLDTHTMLReport(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllTbl_QLDT_HTMLReport", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindAllTblQLDTHTMLReport")
    @ResponseWrapper(localName = "findAllTbl_QLDT_HTMLReportResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindAllTblQLDTHTMLReportResponse")
    @WebMethod(operationName = "findAllTbl_QLDT_HTMLReport")
    public java.util.List<com.lb.jwitter.service.TblQLDTHTMLReport> findAllTblQLDTHTMLReport(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @RequestWrapper(localName = "deleteTbl_QLDT_HTMLReport", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeleteTblQLDTHTMLReport")
    @ResponseWrapper(localName = "deleteTbl_QLDT_HTMLReportResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeleteTblQLDTHTMLReportResponse")
    @WebMethod(operationName = "deleteTbl_QLDT_HTMLReport")
    public void deleteTblQLDTHTMLReport(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @RequestWrapper(localName = "updateTbl_QLDT_HTMLReport", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.UpdateTblQLDTHTMLReport")
    @ResponseWrapper(localName = "updateTbl_QLDT_HTMLReportResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.UpdateTblQLDTHTMLReportResponse")
    @WebMethod(operationName = "updateTbl_QLDT_HTMLReport")
    public void updateTblQLDTHTMLReport(
        @WebParam(name = "arg0", targetNamespace = "")
        com.lb.jwitter.service.TblQLDTHTMLReport arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTbl_QLDT_HTMLReport", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.GetTblQLDTHTMLReport")
    @ResponseWrapper(localName = "getTbl_QLDT_HTMLReportResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.GetTblQLDTHTMLReportResponse")
    @WebMethod(operationName = "getTbl_QLDT_HTMLReport")
    public com.lb.jwitter.service.TblQLDTHTMLReport getTblQLDTHTMLReport(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "countTbl_QLDT_HTMLReportByCondition", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CountTblQLDTHTMLReportByCondition")
    @ResponseWrapper(localName = "countTbl_QLDT_HTMLReportByConditionResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CountTblQLDTHTMLReportByConditionResponse")
    @WebMethod(operationName = "countTbl_QLDT_HTMLReportByCondition")
    public int countTblQLDTHTMLReportByCondition(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.lb.jwitter.service.ConditionReport> arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createTbl_QLDT_HTMLReport", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CreateTblQLDTHTMLReport")
    @ResponseWrapper(localName = "createTbl_QLDT_HTMLReportResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CreateTblQLDTHTMLReportResponse")
    @WebMethod(operationName = "createTbl_QLDT_HTMLReport")
    public java.lang.Long createTblQLDTHTMLReport(
        @WebParam(name = "arg0", targetNamespace = "")
        com.lb.jwitter.service.TblQLDTHTMLReport arg0
    );

    @RequestWrapper(localName = "deleteListTbl_QLDT_HTMLReport", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeleteListTblQLDTHTMLReport")
    @ResponseWrapper(localName = "deleteListTbl_QLDT_HTMLReportResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeleteListTblQLDTHTMLReportResponse")
    @WebMethod(operationName = "deleteListTbl_QLDT_HTMLReport")
    public void deleteListTblQLDTHTMLReport(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.String> arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findColumnTbl_QLDT_HTMLReportByCondition", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindColumnTblQLDTHTMLReportByCondition")
    @ResponseWrapper(localName = "findColumnTbl_QLDT_HTMLReportByConditionResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindColumnTblQLDTHTMLReportByConditionResponse")
    @WebMethod(operationName = "findColumnTbl_QLDT_HTMLReportByCondition")
    public java.util.List<java.lang.Object> findColumnTblQLDTHTMLReportByCondition(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.lb.jwitter.service.ConditionReport> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<java.lang.String> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findTbl_QLDT_HTMLReportByCondition", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindTblQLDTHTMLReportByCondition")
    @ResponseWrapper(localName = "findTbl_QLDT_HTMLReportByConditionResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindTblQLDTHTMLReportByConditionResponse")
    @WebMethod(operationName = "findTbl_QLDT_HTMLReportByCondition")
    public java.util.List<com.lb.jwitter.service.TblQLDTHTMLReport> findTblQLDTHTMLReportByCondition(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.lb.jwitter.service.ConditionReport> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    );
}
