
package com.lb.jwitter.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import com.lb.jwitter.service.TblQLDTLTOptionGroupService;

/**
 * This class was generated by Apache CXF 2.0.9
 * Mon Sep 05 09:39:25 ICT 2016
 * Generated source version: 2.0.9
 * 
 */

@WebServiceClient(name = "Tbl_QLDTLT_OptionGroupServiceService", 
                  wsdlLocation = "file:/C:/PROJECT/VIET%20SOLUTION/CODE%20MAU/WEB%20SERVICE/CORE-Client/src/main/resources/wsdl/core/Tbl_QLDTLT_OptionGroupService.wsdl",
                  targetNamespace = "http://service.jwitter.lb.com/") 
public class TblQLDTLTOptionGroupServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://service.jwitter.lb.com/", "Tbl_QLDTLT_OptionGroupServiceService");
    public final static QName TblQLDTLTOptionGroupServicePort = new QName("http://service.jwitter.lb.com/", "Tbl_QLDTLT_OptionGroupServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/PROJECT/VIET%20SOLUTION/CODE%20MAU/WEB%20SERVICE/CORE-Client/src/main/resources/wsdl/core/Tbl_QLDTLT_OptionGroupService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/C:/PROJECT/VIET%20SOLUTION/CODE%20MAU/WEB%20SERVICE/CORE-Client/src/main/resources/wsdl/core/Tbl_QLDTLT_OptionGroupService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public TblQLDTLTOptionGroupServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TblQLDTLTOptionGroupServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TblQLDTLTOptionGroupServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns TblQLDTLTOptionGroupServicePort
     */
    @WebEndpoint(name = "Tbl_QLDTLT_OptionGroupServicePort")
    public TblQLDTLTOptionGroupService getTblQLDTLTOptionGroupServicePort() {
        return super.getPort(TblQLDTLTOptionGroupServicePort, TblQLDTLTOptionGroupService.class);
    }

}
