
package com.lb.jwitter.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.0.9
 * Mon Sep 05 09:39:18 ICT 2016
 * Generated source version: 2.0.9
 * 
 */

@WebService(targetNamespace = "http://service.jwitter.lb.com/", name = "Tbl_QLDT_HTMLReport_ParamService")

public interface TblQLDTHTMLReportParamService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createTbl_QLDT_HTMLReport_Param", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CreateTblQLDTHTMLReportParam")
    @ResponseWrapper(localName = "createTbl_QLDT_HTMLReport_ParamResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CreateTblQLDTHTMLReportParamResponse")
    @WebMethod(operationName = "createTbl_QLDT_HTMLReport_Param")
    public java.lang.Long createTblQLDTHTMLReportParam(
        @WebParam(name = "arg0", targetNamespace = "")
        com.lb.jwitter.service.TblQLDTHTMLReportParam arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryHQLTbl_QLDT_HTMLReport_Param", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.QueryHQLTblQLDTHTMLReportParam")
    @ResponseWrapper(localName = "queryHQLTbl_QLDT_HTMLReport_ParamResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.QueryHQLTblQLDTHTMLReportParamResponse")
    @WebMethod(operationName = "queryHQLTbl_QLDT_HTMLReport_Param")
    public java.util.List<com.lb.jwitter.service.TblQLDTHTMLReportParam> queryHQLTblQLDTHTMLReportParam(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllTbl_QLDT_HTMLReport_Param", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindAllTblQLDTHTMLReportParam")
    @ResponseWrapper(localName = "findAllTbl_QLDT_HTMLReport_ParamResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindAllTblQLDTHTMLReportParamResponse")
    @WebMethod(operationName = "findAllTbl_QLDT_HTMLReport_Param")
    public java.util.List<com.lb.jwitter.service.TblQLDTHTMLReportParam> findAllTblQLDTHTMLReportParam(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findColumnTbl_QLDT_HTMLReport_ParamByCondition", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindColumnTblQLDTHTMLReportParamByCondition")
    @ResponseWrapper(localName = "findColumnTbl_QLDT_HTMLReport_ParamByConditionResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindColumnTblQLDTHTMLReportParamByConditionResponse")
    @WebMethod(operationName = "findColumnTbl_QLDT_HTMLReport_ParamByCondition")
    public java.util.List<java.lang.Object> findColumnTblQLDTHTMLReportParamByCondition(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.lb.jwitter.service.ConditionReport> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<java.lang.String> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3
    );

    @RequestWrapper(localName = "deleteListTbl_QLDT_HTMLReport_Param", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeleteListTblQLDTHTMLReportParam")
    @ResponseWrapper(localName = "deleteListTbl_QLDT_HTMLReport_ParamResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeleteListTblQLDTHTMLReportParamResponse")
    @WebMethod(operationName = "deleteListTbl_QLDT_HTMLReport_Param")
    public void deleteListTblQLDTHTMLReportParam(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.String> arg0
    );

    @RequestWrapper(localName = "deleteTbl_QLDT_HTMLReport_Param", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeleteTblQLDTHTMLReportParam")
    @ResponseWrapper(localName = "deleteTbl_QLDT_HTMLReport_ParamResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeleteTblQLDTHTMLReportParamResponse")
    @WebMethod(operationName = "deleteTbl_QLDT_HTMLReport_Param")
    public void deleteTblQLDTHTMLReportParam(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "countTbl_QLDT_HTMLReport_ParamByCondition", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CountTblQLDTHTMLReportParamByCondition")
    @ResponseWrapper(localName = "countTbl_QLDT_HTMLReport_ParamByConditionResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CountTblQLDTHTMLReportParamByConditionResponse")
    @WebMethod(operationName = "countTbl_QLDT_HTMLReport_ParamByCondition")
    public int countTblQLDTHTMLReportParamByCondition(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.lb.jwitter.service.ConditionReport> arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTbl_QLDT_HTMLReport_Param", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.GetTblQLDTHTMLReportParam")
    @ResponseWrapper(localName = "getTbl_QLDT_HTMLReport_ParamResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.GetTblQLDTHTMLReportParamResponse")
    @WebMethod(operationName = "getTbl_QLDT_HTMLReport_Param")
    public com.lb.jwitter.service.TblQLDTHTMLReportParam getTblQLDTHTMLReportParam(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findTbl_QLDT_HTMLReport_ParamByCondition", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindTblQLDTHTMLReportParamByCondition")
    @ResponseWrapper(localName = "findTbl_QLDT_HTMLReport_ParamByConditionResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindTblQLDTHTMLReportParamByConditionResponse")
    @WebMethod(operationName = "findTbl_QLDT_HTMLReport_ParamByCondition")
    public java.util.List<com.lb.jwitter.service.TblQLDTHTMLReportParam> findTblQLDTHTMLReportParamByCondition(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.lb.jwitter.service.ConditionReport> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    );

    @RequestWrapper(localName = "updateTbl_QLDT_HTMLReport_Param", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.UpdateTblQLDTHTMLReportParam")
    @ResponseWrapper(localName = "updateTbl_QLDT_HTMLReport_ParamResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.UpdateTblQLDTHTMLReportParamResponse")
    @WebMethod(operationName = "updateTbl_QLDT_HTMLReport_Param")
    public void updateTblQLDTHTMLReportParam(
        @WebParam(name = "arg0", targetNamespace = "")
        com.lb.jwitter.service.TblQLDTHTMLReportParam arg0
    );
}
