
package com.lb.jwitter.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.0.9
 * Mon Sep 05 09:39:20 ICT 2016
 * Generated source version: 2.0.9
 * 
 */

@WebService(targetNamespace = "http://service.jwitter.lb.com/", name = "Tbl_TaiKhoanService")

public interface TblTaiKhoanService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createtbl_TaiKhoan", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CreatetblTaiKhoan")
    @ResponseWrapper(localName = "createtbl_TaiKhoanResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CreatetblTaiKhoanResponse")
    @WebMethod(operationName = "createtbl_TaiKhoan")
    public java.lang.Long createtblTaiKhoan(
        @WebParam(name = "arg0", targetNamespace = "")
        com.lb.jwitter.service.TblTaiKhoan arg0
    );

    @RequestWrapper(localName = "deletetbl_TaiKhoan", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeletetblTaiKhoan")
    @ResponseWrapper(localName = "deletetbl_TaiKhoanResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeletetblTaiKhoanResponse")
    @WebMethod(operationName = "deletetbl_TaiKhoan")
    public void deletetblTaiKhoan(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "gettbl_TaiKhoan", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.GettblTaiKhoan")
    @ResponseWrapper(localName = "gettbl_TaiKhoanResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.GettblTaiKhoanResponse")
    @WebMethod(operationName = "gettbl_TaiKhoan")
    public com.lb.jwitter.service.TblTaiKhoan gettblTaiKhoan(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findtbl_TaiKhoanByCondition", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindtblTaiKhoanByCondition")
    @ResponseWrapper(localName = "findtbl_TaiKhoanByConditionResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindtblTaiKhoanByConditionResponse")
    @WebMethod(operationName = "findtbl_TaiKhoanByCondition")
    public java.util.List<com.lb.jwitter.service.TblTaiKhoan> findtblTaiKhoanByCondition(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.lb.jwitter.service.ConditionReport> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "counttbl_TaiKhoanByCondition", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CounttblTaiKhoanByCondition")
    @ResponseWrapper(localName = "counttbl_TaiKhoanByConditionResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.CounttblTaiKhoanByConditionResponse")
    @WebMethod(operationName = "counttbl_TaiKhoanByCondition")
    public int counttblTaiKhoanByCondition(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.lb.jwitter.service.ConditionReport> arg0
    );

    @RequestWrapper(localName = "deleteListtbl_TaiKhoan", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeleteListtblTaiKhoan")
    @ResponseWrapper(localName = "deleteListtbl_TaiKhoanResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.DeleteListtblTaiKhoanResponse")
    @WebMethod(operationName = "deleteListtbl_TaiKhoan")
    public void deleteListtblTaiKhoan(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.String> arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAlltbl_TaiKhoan", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindAlltblTaiKhoan")
    @ResponseWrapper(localName = "findAlltbl_TaiKhoanResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.FindAlltblTaiKhoanResponse")
    @WebMethod(operationName = "findAlltbl_TaiKhoan")
    public java.util.List<com.lb.jwitter.service.TblTaiKhoan> findAlltblTaiKhoan(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @RequestWrapper(localName = "updatetbl_TaiKhoan", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.UpdatetblTaiKhoan")
    @ResponseWrapper(localName = "updatetbl_TaiKhoanResponse", targetNamespace = "http://service.jwitter.lb.com/", className = "com.lb.jwitter.service.UpdatetblTaiKhoanResponse")
    @WebMethod(operationName = "updatetbl_TaiKhoan")
    public void updatetblTaiKhoan(
        @WebParam(name = "arg0", targetNamespace = "")
        com.lb.jwitter.service.TblTaiKhoan arg0
    );
}
